# Generated by Django 6.0.7 on 2026-07-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FLEET_MANAGER', 'Fleet Manager'), ('DISPATCHER', 'Dispatcher'), ('SAFETY_OFFICER', 'Safety Officer'), ('FINANCIAL_ANALYST', 'Financial Analyst')], default='FLEET_MANAGER', max_length=30),
        ),
    ]
